const CONSTANTS={
    BLOCK_HEADER_HEIGHT:20,
    BLOCK_RESIZE_BUTTON_HEIGHT:10,
    BLOCK_RESIZE_BUTTON_WIDTH:10,
    MIN_BLOCK_HEIGHT:40,
    MIN_BLOCK_WIDTH:40,
    BLOCK_REMOVE_BUTTON_WIDTH:20
};
export default CONSTANTS;